### ISSUE TITLE
Does cert auto-renew? 

### ISSUE THREAD

**Issue by tenajsystems** [broadinstitute/puppet-certs#40]
I am looking into possibly using this module to generate certs and was wondering if this module auto renews the certs when it is about to expire? Please let me know what your thoughts are on this. Also, are the certs self-signed?

Thank you.

**Comment by rcalixte** [comment]
Hi @tenajsystems, this module does not currently generate certs or renew them with your CA. Any certificates can be used with the module, either self-signed or signed by an external CA.

If you're looking for a CA that you can use to automate generation or renewal of certificates, I would recommend Let's Encrypt (https://github.com/letsencrypt and https://letsencrypt.org). They have phenomenal resources from documentation to an API available.

You can use this module to deploy your certificates to your nodes in your environment though! :wink:
