### ISSUE TITLE
erros during puppet agent run

### ISSUE THREAD

**Issue by alexseys** [broadinstitute/puppet-certs#50]
Hi 
Any hints on resolving this error:
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not find resource 'Service[httpd]' in parameter 'notify' (file: /etc/puppetlabs/code/environments/production/modules/certs/manifests/site.pp, line: 457) on node agent.example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

httpd is installed on this agent

Thank you!

**Comment by rcalixte** [comment]
Hi @alexseys, this likely means the service isn't defined in your catalog. Are you currently managing httpd with Puppet? If not, you can set `service: false` in your config and that should resolve it.

**Comment by alexseys** [comment]
Thank you very much sir!
Issue resolved
